# Generated by Django 5.2.8 on 2026-03-11 04:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_policy_tools', '0010_alter_privacypolicy_text_alter_privacypolicy_text_de_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'ordering': ['-published_at', '-version'], 'verbose_name': 'Privacy Policy', 'verbose_name_plural': 'Privacy Policies'},
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='confirm_button_text_de',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='confirm_button_text_en',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='confirm_checkbox_text_de',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='confirm_checkbox_text_en',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='text_de',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='title_en',
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Version'),
        ),
    ]
